language: rust

os:
- linux
- osx
- windows

rust:
- stable

cache: cargo

addons:
  apt:
    packages:
      - libgl1-mesa-dev

branches:
  only:
  - master

before_install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    REG ADD "HKLM\SYSTEM\CurrentControlSet\Control\FileSystem" /v LongPathsEnabled /t REG_DWORD /d 1 /f
  fi

script:
- travis_wait 30 cargo build --release

deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis.deploy.sh
