language: rust

os:
- linux
- osx
- windows

rust:
- stable

cache: cargo

addons:
  apt:
    packages:
      - libgl1-mesa-dev

branches:
  only:
  - master

before_install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    ./scripts/enable_long_paths.bat;
    export PYTHONHTTPSVERIFY=0;
    choco install openssl;
    certutil -generateSSTFromWU roots.sst && certutil -addstore -f root roots.sst && del roots.sst;
  fi

script:
- travis_wait 30 cargo build --release

deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis.deploy.sh
