language: rust

os:
- linux
- osx
- windows

rust:
- stable

cache: cargo

addons:
  apt:
    packages:
      - libgl1-mesa-dev

branches:
  only:
  - master

script:
- travis_wait 30 cargo build --release

deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis.deploy.sh
