language: rust

os:
- linux
- osx
- windows

rust:
- stable

addons:
  apt:
    packages:
      - libgl1-mesa-dev

branches:
  only:
  - master

before_install:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    echo "DisableArchiveScanning...";
    powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableArchiveScanning \$true'";
    echo "DisableBehaviorMonitoring...";
    powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableBehaviorMonitoring \$true'";
    echo "DisableRealtimeMonitoring...";
    powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableRealtimeMonitoring \$true'";
    ./scripts/enable_long_paths.bat;
    export PYTHONHTTPSVERIFY=0;
    choco install openssl;
    certutil -generateSSTFromWU roots.sst && certutil -addstore -f root roots.sst;
    git config --global sync-deps.disable true;
  fi

script:
- travis_wait 30 cargo build --release

deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis.deploy.sh
