[package]
name = "libskia"
version = "0.1.0"
authors = ["Aliaksei Syrel <alex.syrel@gmail.com>"]

[dependencies]
typename = "0.1.1"
float-cmp = "0.6.0"
skia-safe = { git = "https://github.com/rust-skia/rust-skia", rev = "b033247501df875328c525714fceafec52de6389" }
libc = "0.2.65"
boxer = { git = "https://github.com/feenkcom/gtoolkit-boxer" }
crossbeam = "0.7.3"
num_cpus = "1.0"

[lib]
name = "Skia"
crate-type = ["cdylib"]

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

[profile.release]
opt-level = 3