[workspace]
resolver = "2"

members = [
    "libskia",
    "libskia-builder",
]

exclude = [ "target" ]

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = 'thin'

[profile.release]
opt-level = 3
lto = 'thin'
debug = true