[package]
name = "libskia-builder"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "builder"
path = "src/main.rs"

[dependencies]
shared-library-builder = { git = "https://github.com/feenkcom/shared-library-builder-rs" }
libskia-library = { path = "../library" }