[package]
name = "libskia-builder"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "builder"
path = "src/main.rs"

[dependencies]
shared-library-builder = { git = "https://github.com/feenkcom/shared-library-builder-rs" }