[package]
name = "libskia"
version = "0.1.0"
authors = ["Aliaksei Syrel <alex.syrel@gmail.com>"]
edition = "2021"

[dependencies]
skia-safe = ">=0.55.0"
typename = "0.1.1"
float-cmp = "0.6.0"
ordered-float = "1.0.2"
libc = "0.2.68"
crossbeam = "0.8.2"
num_cpus = "1.0"
byteorder = "1.3.4"
num_enum = "0.4.3"
widestring = "0.4.2"
log = "0.4"
env_logger = "0.8"
fps_counter = "2.0.0"
lazy_static = "1.4.0"
anyhow = "1.0.56"
metal = { version = "0.23.1", optional = true }
cocoa = { version = "0.24.0", optional = true }
core-graphics-types = { version = "0.1.1", optional = true }
foreign-types-shared = { version = "0.1.1", optional = true }
boxer = { git = "https://github.com/feenkcom/gtoolkit-boxer", rev = "fdc253f9559acd60e777b0357ec9d6efeff86577" }
compositor = { git = "https://github.com/feenkcom/compositor-rs" }
compositor-skia = { git = "https://github.com/feenkcom/compositor-rs" }
compositor-ffi = { git = "https://github.com/feenkcom/compositor-rs" }
compositor-skia-ffi = { git = "https://github.com/feenkcom/compositor-rs" }

#boxer = { path = "../../gtoolkit-boxer/boxer" }
#compositor = { path = "../../compositor-rs/compositor" }
#compositor-skia = { path = "../../compositor-rs/compositor-skia" }
#compositor-ffi = { path = "../../compositor-rs/compositor-ffi" }
#compositor-skia-ffi = { path = "../../compositor-rs/compositor-skia-ffi" }

[dependencies.mozangle]
git = "https://github.com/syrel/mozangle"
rev = "8ad3227cbfe59b9ddbaa95379b5d45804427630d"
optional = true
features = [ "egl" ]

[dependencies.windows]
version = "0.34.0"
optional = true
features = [
    "alloc",
    "Foundation",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct3D12",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_System_WinRT",
    "Win32_System_WinRT_Direct3D11",
    "Win32_System_WinRT_Graphics_Capture",
    "Graphics_DirectX_Direct3D11",
]

[features]
textlayout = ["skia-safe/textlayout"]
gl = ["skia-safe/gl"]
d3d = ["skia-safe/d3d", "windows" ]
angle = ["gl", "mozangle"]
x11 = ["skia-safe/x11"]
shaper = ["skia-safe/shaper"]
default = ["gl", "textlayout"]
skia_windows = [ "d3d", "angle" ]
skia_mac = ["skia-safe/metal", "metal", "cocoa", "foreign-types-shared", "core-graphics-types" ]
skia_linux = ["x11", "shaper"]

[lib]
name = "Skia"
crate-type = ["cdylib"]