[package]
name = "libskia-library"
version = "0.2.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
shared-library-builder = { git = "https://github.com/feenkcom/shared-library-builder-rs", features = ["git-location"] }